GET http://localhost:8080/profile/skills?id=111

###

GET http://localhost:8080/profile/skills?id=112

###

POST http://localhost:8080/profile/skills/
Content-Type: application/json

{
  "specialization": {
    "category": "Test Category",
    "subCategory": "Test Sub Category"
  },
  "operatingSystems": [
    "Test System"
  ],
  "dataBases": [
    "Test Data Base"
  ]
}

###

PUT http://localhost:8080/profile/skills/
Content-Type: application/json

{
  "specialization": {
    "category": "Update Category",
    "subCategory": "Update Sub Category"
  },
  "operatingSystems": [
    "Update System"
  ],
  "dataBases": [
    "Update Data Base"
  ]
}

###

DELETE http://localhost:8080/profile/skills/
Content-Type: application/json

{
  "profileId": "111"
}