GET http://localhost:8080/profile/education/?id=123
Content-Type: application/json

{
  "id": 123
}

###

PUT http://localhost:8080/profile/education/
Content-Type: application/json

{
  "additionalEducation": [
    {
      "nameOfInstitution": "OTUS",
      "courseName": "Kotlin",
      "yearOfCompletion": "2021"
    }
  ]
}

###

DELETE http://localhost:8080/profile/education/
Content-Type: application/json

{
  "id": 123
}

###

POST http://localhost:8080/profile/education/
Content-Type: application/json

{
  "additionalEducation": [
    {
      "nameOfInstitution": "OTUS",
      "courseName": "Kotlin",
      "yearOfCompletion": "2020"
    }
  ]
}