###
GET http://localhost:8080/profile/education/?id=test-id
test:inmemory
Content-Type: application/json

###

PUT http://localhost:8080/profile/education/
Content-Type: application/json

{
  "profileId": "test-id",
  "additionalEducation": [
    {
      "id": "test-id",
      "nameOfInstitution": "OTUS",
      "courseName": "Kotlin",
      "yearOfCompletion": "2021"
    }
  ],
  "debug": {
    "db": "TEST"
  }
}

###

DELETE http://localhost:8080/profile/education/
Content-Type: application/json

{
  "profileId": "test-id",
  "debug": {
    "db": "TEST"
  }
}

###

POST http://localhost:8080/profile/education/
Content-Type: application/json

{
  "additionalEducation": [
    {
      "nameOfInstitution": "OTUS",
      "courseName": "Kotlin",
      "yearOfCompletion": "2020"
    }
  ],
  "debug": {
    "db": "TEST"
  }
}